<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>HW 1 Carlo</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="HW1_Carlo_files/libs/clipboard/clipboard.min.js"></script>
<script src="HW1_Carlo_files/libs/quarto-html/quarto.js"></script>
<script src="HW1_Carlo_files/libs/quarto-html/popper.min.js"></script>
<script src="HW1_Carlo_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="HW1_Carlo_files/libs/quarto-html/anchor.min.js"></script>
<link href="HW1_Carlo_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="HW1_Carlo_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="HW1_Carlo_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="HW1_Carlo_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="HW1_Carlo_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">HW 1 Carlo</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="homework-1-linear-regressions-in-r" class="level1">
<h1>Homework 1! Linear Regressions in R</h1>
<p>Catherine Carlo,</p>
<p>July 18, 2023</p>
<section id="executive-summary" class="level2">
<h2 class="anchored" data-anchor-id="executive-summary">Executive Summary</h2>
<p>The goal of this report is to predict employee salary. To do this, I created and pruned a linear regression model. From the final model, these are the important variables: Count of special projects assigned to each employee, Employee Tenure, employee Department, and employee Manager. I recommend using this model because it will be accurate about 3/5 of the time. This model takes 59% of randomness into consideration when predicting Salary.</p>
</section>
<section id="set-up" class="level2">
<h2 class="anchored" data-anchor-id="set-up">Set-Up</h2>
<p>here are all the packages we’ll be using… let’s load them in.</p>
<p>now let’s load in the data and remove unnecessary predictors (zip, state, term reason, employee name)/</p>
<p>Now adding age and time employee has been employed. We are using the June 30, 2019 as our date equal to today.</p>
<p>We can remove the DOB, Hire date &amp; termination date, join all the dataframes we created earlier into one big dataframe, and take a look at the first few rows.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>  EmpID Married GenderCode EmpStatusID DeptID PerfScoreID FromDiversityJobFair
1 10026       0          1           1      5           4                    0
2 10084       1          3           5      3           3                    0
3 10196       1          2           5      5           3                    0
4 10088       1          2           1      5           3                    0
5 10069       0          2           5      5           3                    0
6 10002       0          2           1      5           4                    0
  Salary Termd ManagerID EngagementSurvey EmpSatisfaction SpecialProjectsCount
1  62506     0        22             4.60               5                    0
2 104437     1         4             4.96               3                    6
3  64955     1        20             3.02               3                    0
4  64991     0        16             4.84               5                    0
5  50825     1        39             5.00               4                    0
6  57568     0        11             5.00               5                    0
  DaysLateLast30 Absences       Age TimeEmployed    ManagerName
1              0        1  7.986995     7.986995 Michael Albert
2              0       17  4.252567     1.215606     Simon Roup
3              0        3  7.986995     1.223819 Kissy Sullivan
4              0       15 11.477755    11.477755   Elijiah Gray
5              0        2  7.970568     5.158111 Webster Butler
6              0       15  7.472279     7.472279       Amy Dunn
  PerformanceScore        Department       EmploymentStatus
1          Exceeds Production                        Active
2      Fully Meets             IT/IS Voluntarily Terminated
3      Fully Meets Production        Voluntarily Terminated
4      Fully Meets Production                        Active
5      Fully Meets Production        Voluntarily Terminated
6          Exceeds Production                        Active</code></pre>
</div>
</div>
<p>Now we’ll look at the predictor information a little more closely.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">df_original</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">311</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">21</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">character</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">17</td>
</tr>
<tr class="even">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 22%">
<col style="width: 13%">
<col style="width: 18%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">empty</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: right;">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ManagerName</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">PerformanceScore</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Department</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">EmploymentStatus</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 18%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">EmpID</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">10156.00</td>
<td style="text-align: right;">89.92</td>
<td style="text-align: right;">10001.00</td>
<td style="text-align: right;">10078.50</td>
<td style="text-align: right;">10156.00</td>
<td style="text-align: right;">10233.50</td>
<td style="text-align: right;">10311.00</td>
<td style="text-align: left;">▇▇▇▇▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">Married</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.40</td>
<td style="text-align: right;">0.49</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">▇▁▁▁▅</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GenderCode</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.71</td>
<td style="text-align: right;">0.61</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">3.00</td>
<td style="text-align: left;">▆▁▇▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">EmpStatusID</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.29</td>
<td style="text-align: right;">1.83</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: left;">▇▁▁▁▃</td>
</tr>
<tr class="odd">
<td style="text-align: left;">DeptID</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4.61</td>
<td style="text-align: right;">1.08</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">6.00</td>
<td style="text-align: left;">▁▂▁▇▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">PerfScoreID</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.98</td>
<td style="text-align: right;">0.59</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">3.00</td>
<td style="text-align: right;">3.00</td>
<td style="text-align: right;">3.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: left;">▁▁▁▇▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FromDiversityJobFair</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.09</td>
<td style="text-align: right;">0.29</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">Salary</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">69020.68</td>
<td style="text-align: right;">25156.64</td>
<td style="text-align: right;">45046.00</td>
<td style="text-align: right;">55501.50</td>
<td style="text-align: right;">62810.00</td>
<td style="text-align: right;">72036.00</td>
<td style="text-align: right;">250000.00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Termd</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.33</td>
<td style="text-align: right;">0.47</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">▇▁▁▁▅</td>
</tr>
<tr class="even">
<td style="text-align: left;">ManagerID</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">13.52</td>
<td style="text-align: right;">9.41</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">12.00</td>
<td style="text-align: right;">19.00</td>
<td style="text-align: right;">39.00</td>
<td style="text-align: left;">▇▆▆▁▂</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EngagementSurvey</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4.11</td>
<td style="text-align: right;">0.79</td>
<td style="text-align: right;">1.12</td>
<td style="text-align: right;">3.69</td>
<td style="text-align: right;">4.28</td>
<td style="text-align: right;">4.70</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: left;">▁▁▂▅▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">EmpSatisfaction</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.89</td>
<td style="text-align: right;">0.91</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">3.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: left;">▁▁▇▇▇</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SpecialProjectsCount</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.22</td>
<td style="text-align: right;">2.35</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">8.00</td>
<td style="text-align: left;">▇▁▁▂▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">DaysLateLast30</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.41</td>
<td style="text-align: right;">1.29</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">6.00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Absences</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">10.24</td>
<td style="text-align: right;">5.85</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">10.00</td>
<td style="text-align: right;">15.00</td>
<td style="text-align: right;">20.00</td>
<td style="text-align: left;">▇▆▅▇▆</td>
</tr>
<tr class="even">
<td style="text-align: left;">Age</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">6.40</td>
<td style="text-align: right;">1.95</td>
<td style="text-align: right;">0.98</td>
<td style="text-align: right;">4.77</td>
<td style="text-align: right;">6.36</td>
<td style="text-align: right;">7.97</td>
<td style="text-align: right;">13.47</td>
<td style="text-align: left;">▁▆▇▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TimeEmployed</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5.05</td>
<td style="text-align: right;">2.27</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">3.83</td>
<td style="text-align: right;">4.98</td>
<td style="text-align: right;">6.48</td>
<td style="text-align: right;">13.47</td>
<td style="text-align: left;">▃▇▆▁▁</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>     EmpID          Married         GenderCode     EmpStatusID   
 Min.   :10001   Min.   :0.0000   Min.   :1.000   Min.   :1.000  
 1st Qu.:10078   1st Qu.:0.0000   1st Qu.:1.000   1st Qu.:1.000  
 Median :10156   Median :0.0000   Median :2.000   Median :1.000  
 Mean   :10156   Mean   :0.3987   Mean   :1.707   Mean   :2.286  
 3rd Qu.:10234   3rd Qu.:1.0000   3rd Qu.:2.000   3rd Qu.:5.000  
 Max.   :10311   Max.   :1.0000   Max.   :3.000   Max.   :5.000  
     DeptID       PerfScoreID    FromDiversityJobFair     Salary      
 Min.   :1.000   Min.   :1.000   Min.   :0.00000      Min.   : 45046  
 1st Qu.:5.000   1st Qu.:3.000   1st Qu.:0.00000      1st Qu.: 55502  
 Median :5.000   Median :3.000   Median :0.00000      Median : 62810  
 Mean   :4.611   Mean   :2.977   Mean   :0.09325      Mean   : 69021  
 3rd Qu.:5.000   3rd Qu.:3.000   3rd Qu.:0.00000      3rd Qu.: 72036  
 Max.   :6.000   Max.   :4.000   Max.   :1.00000      Max.   :250000  
     Termd          ManagerID     EngagementSurvey EmpSatisfaction
 Min.   :0.0000   Min.   : 2.00   Min.   :1.12     Min.   :1.000  
 1st Qu.:0.0000   1st Qu.: 5.00   1st Qu.:3.69     1st Qu.:3.000  
 Median :0.0000   Median :12.00   Median :4.28     Median :4.000  
 Mean   :0.3344   Mean   :13.52   Mean   :4.11     Mean   :3.891  
 3rd Qu.:1.0000   3rd Qu.:19.00   3rd Qu.:4.70     3rd Qu.:5.000  
 Max.   :1.0000   Max.   :39.00   Max.   :5.00     Max.   :5.000  
 SpecialProjectsCount DaysLateLast30      Absences          Age         
 Min.   :0.000        Min.   :0.0000   Min.   : 1.00   Min.   : 0.9754  
 1st Qu.:0.000        1st Qu.:0.0000   1st Qu.: 5.00   1st Qu.: 4.7659  
 Median :0.000        Median :0.0000   Median :10.00   Median : 6.3607  
 Mean   :1.219        Mean   :0.4148   Mean   :10.24   Mean   : 6.3992  
 3rd Qu.:0.000        3rd Qu.:0.0000   3rd Qu.:15.00   3rd Qu.: 7.9706  
 Max.   :8.000        Max.   :6.0000   Max.   :20.00   Max.   :13.4709  
  TimeEmployed      ManagerName        PerformanceScore    Department       
 Min.   : 0.07118   Length:311         Length:311         Length:311        
 1st Qu.: 3.82615   Class :character   Class :character   Class :character  
 Median : 4.98083   Mode  :character   Mode  :character   Mode  :character  
 Mean   : 5.04712                                                           
 3rd Qu.: 6.47536                                                           
 Max.   :13.47091                                                           
 EmploymentStatus  
 Length:311        
 Class :character  
 Mode  :character  
                   
                   
                   </code></pre>
</div>
</div>
<p>Removing original IDs, salaries over 170,000, and the predictor <code>termd</code>.</p>
<p>Changing some of the categorical variables to their text meanings so it makes sense in my brain.</p>
<p>To understand the data better, it’s time for some visuals! Starting with the numeric predictors, here are their histograms.</p>
<section id="findings" class="level4">
<h4 class="anchored" data-anchor-id="findings">Findings:</h4>
<ul>
<li><p>almost no employees have been late in last 30 days</p></li>
<li><p>Age is skewed so let’s transform it with log and add it to <code>df_original</code>.</p></li>
</ul>
<p>Next is visualizing the categorical variables. I will do this with bar count graphs showing the breakdown of category values by predictor.</p>
</section>
<section id="findings-1" class="level4">
<h4 class="anchored" data-anchor-id="findings-1">Findings:</h4>
<ul>
<li><p>Very few employees are from the diversity job fair</p></li>
<li><p>~1/2 of employees are married</p></li>
<li><p>Board of directors is the manger for only one employee that makes &lt;$170,000</p></li>
<li><p>Most employees work in production &amp; also fully meet performance expectations</p></li>
</ul>
<p>Visualizing it all together now</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="HW1_Carlo_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="384"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="findings-2" class="level4">
<h4 class="anchored" data-anchor-id="findings-2">Findings:</h4>
<ul>
<li><p>Variables over 0.5 should be monitored for high correlation… I need to keep in mind multicolinearity when creating and pruning the model.</p></li>
<li><p>We can see outliers in the bar plots of these predictors.</p></li>
</ul>
</section>
</section>
<section id="modeling-time" class="level2">
<h2 class="anchored" data-anchor-id="modeling-time">Modeling time :)</h2>
<p>For our first foray into linear regression modeling with this data, we will use all original, non-transformed predictors. This means no <code>age_log</code>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
stats::lm(formula = Salary ~ . - age_log, data = data)

Residuals:
   Min     1Q Median     3Q    Max 
-44211  -6135   -192   6018  53648 

Coefficients: (2 not defined because of singularities)
                                       Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                             44095.5    12370.5   3.565 0.000430 ***
MarriedYes                               -433.6     1492.5  -0.290 0.771655    
GenderCode                              -1498.3     2788.9  -0.537 0.591546    
DeptID                                  13040.5     2371.5   5.499 8.79e-08 ***
FromDiversityJobFairYes                  2749.3     2632.7   1.044 0.297287    
EngagementSurvey                          457.6     1158.2   0.395 0.693119    
EmpSatisfaction                           842.6      821.5   1.026 0.305954    
SpecialProjectsCount                    -2204.7     1295.0  -1.702 0.089803 .  
DaysLateLast30                           -160.9     1446.1  -0.111 0.911466    
Absences                                  108.4      122.3   0.886 0.376186    
Age                                       286.3      793.7   0.361 0.718607    
TimeEmployed                             -928.5      672.9  -1.380 0.168800    
ManagerNameBoard of Directors           52501.0    14327.0   3.664 0.000298 ***
ManagerNameBrannon Miller                2891.2     3859.5   0.749 0.454433    
ManagerNameDavid Stanley                -1140.6     3805.5  -0.300 0.764618    
ManagerNameElijiah Gray                  3241.0     3751.7   0.864 0.388415    
ManagerNameJanet King                   16965.3     4219.4   4.021 7.51e-05 ***
ManagerNameJennifer Zamora              20321.9     5947.1   3.417 0.000729 ***
ManagerNameKelley Spirea                  586.2     3900.4   0.150 0.880643    
ManagerNameKetsia Liebig                -1147.1     3834.7  -0.299 0.765066    
ManagerNameKissy Sullivan               -1146.9     3736.1  -0.307 0.759087    
ManagerNameMichael Albert                 600.3     3788.3   0.158 0.874219    
ManagerNamePeter Monroe                   811.0     5826.7   0.139 0.889408    
ManagerNameSimon Roup                    9613.2     6159.0   1.561 0.119720    
ManagerNameWebster Butler               -1724.7     3798.4  -0.454 0.650142    
PerformanceScoreFully Meets              -856.0     2341.1  -0.366 0.714912    
PerformanceScoreImprovement               468.5     6726.2   0.070 0.944517    
DepartmentIT/IS                         12837.3     4268.2   3.008 0.002878 ** 
DepartmentProduction                   -50697.7    10692.9  -4.741 3.43e-06 ***
DepartmentSales                        -67710.8    12130.2  -5.582 5.73e-08 ***
DepartmentSoftware Engineering               NA         NA      NA       NA    
EmploymentStatusTerminated for Cause     1800.7     4009.5   0.449 0.653718    
EmploymentStatusVoluntarily Terminated  -1565.2     3423.6  -0.457 0.647910    
GenderMale                               -734.7     3466.3  -0.212 0.832311    
GenderOther                                  NA         NA      NA       NA    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 12040 on 273 degrees of freedom
Multiple R-squared:  0.6219,    Adjusted R-squared:  0.5776 
F-statistic: 14.03 on 32 and 273 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Lots to take in here. We can see that many predictors have insignificant p values (&gt;0.05). Using glance, we can see a clearer table for the overall statistics of the model.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 14%">
<col style="width: 19%">
<col style="width: 12%">
<col style="width: 14%">
<col style="width: 11%">
<col style="width: 4%">
<col style="width: 16%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">r.squared</th>
<th style="text-align: right;">adj.r.squared</th>
<th style="text-align: right;">sigma</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">df.residual</th>
<th style="text-align: right;">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.6219</td>
<td style="text-align: right;">0.5776</td>
<td style="text-align: right;">12037.29</td>
<td style="text-align: right;">14.0308</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">273</td>
<td style="text-align: right;">306</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
  Model      Pruned_Variables       R_Square Adj_R_Square   MAE
  &lt;chr&gt;      &lt;chr&gt;                     &lt;dbl&gt;        &lt;dbl&gt; &lt;dbl&gt;
1 Full Model All Original Variables    0.622        0.578 8115.</code></pre>
</div>
</div>
<p>Adjusted R Square is not great. It is 0.5776 and is basically equal to flipping a coin. This model currently only explaining 57.8% of variance for this data. When predicted vs actual Salary is plotted, we will likely see data points that are not closely following the model’s slope.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="HW1_Carlo_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="384"></p>
</figure>
</div>
</div>
</div>
<p>That is exactly what we see in the plot. This model leaves much to be desired. Since we mutated age to log(age) before, let’s see if that is any better.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  Model                      Pruned_Variables       R_Square Adj_R_Square   MAE
  &lt;chr&gt;                      &lt;chr&gt;                     &lt;dbl&gt;        &lt;dbl&gt; &lt;dbl&gt;
1 Full Model                 All Original Variables    0.622        0.578 8115.
2 OG Predictors with Log Age Log Age                   0.622        0.577 8127.</code></pre>
</div>
</div>
<p>Age is .5776 &amp; age log is .5775… going with age not age log. <code>PerformanceScore</code> has the highest p value so let’s remove that next.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  Model                      Pruned_Variables       R_Square Adj_R_Square   MAE
  &lt;chr&gt;                      &lt;chr&gt;                     &lt;dbl&gt;        &lt;dbl&gt; &lt;dbl&gt;
1 Full Model                 All Original Variables    0.622        0.578 8115.
2 OG Predictors with Log Age Log Age                   0.622        0.577 8127.
3 - Performance              PerformanceScore          0.622        0.580 8115.</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  Model                      Pruned_Variables       R_Square Adj_R_Square   MAE
  &lt;chr&gt;                      &lt;chr&gt;                     &lt;dbl&gt;        &lt;dbl&gt; &lt;dbl&gt;
1 Full Model                 All Original Variables    0.622        0.578 8115.
2 OG Predictors with Log Age Log Age                   0.622        0.577 8127.
3 - Performance              PerformanceScore          0.622        0.580 8115.
4 - DaysLateLast30           Above + DaysLateLast30    0.622        0.582 8109.</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 5
  Model                      Pruned_Variables       R_Square Adj_R_Square   MAE
  &lt;chr&gt;                      &lt;chr&gt;                     &lt;dbl&gt;        &lt;dbl&gt; &lt;dbl&gt;
1 Full Model                 All Original Variables    0.622        0.578 8115.
2 OG Predictors with Log Age Log Age                   0.622        0.577 8127.
3 - Performance              PerformanceScore          0.622        0.580 8115.
4 - DaysLateLast30           Above + DaysLateLast30    0.622        0.582 8109.
5 Combined Managers          Above + ManagerName       0.608        0.582 8295.</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  Model                      Pruned_Variables       R_Square Adj_R_Square   MAE
  &lt;chr&gt;                      &lt;chr&gt;                     &lt;dbl&gt;        &lt;dbl&gt; &lt;dbl&gt;
1 Full Model                 All Original Variables    0.622        0.578 8115.
2 OG Predictors with Log Age Log Age                   0.622        0.577 8127.
3 - Performance              PerformanceScore          0.622        0.580 8115.
4 - DaysLateLast30           Above + DaysLateLast30    0.622        0.582 8109.
5 Combined Managers          Above + ManagerName       0.608        0.582 8295.
6 - Married                  Above + Married           0.608        0.584 8291.</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 5
  Model                      Pruned_Variables       R_Square Adj_R_Square   MAE
  &lt;chr&gt;                      &lt;chr&gt;                     &lt;dbl&gt;        &lt;dbl&gt; &lt;dbl&gt;
1 Full Model                 All Original Variables    0.622        0.578 8115.
2 OG Predictors with Log Age Log Age                   0.622        0.577 8127.
3 - Performance              PerformanceScore          0.622        0.580 8115.
4 - DaysLateLast30           Above + DaysLateLast30    0.622        0.582 8109.
5 Combined Managers          Above + ManagerName       0.608        0.582 8295.
6 - Married                  Above + Married           0.608        0.584 8291.
7 - Age                      Above + Age               0.608        0.585 8291.</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 5
  Model                      Pruned_Variables       R_Square Adj_R_Square   MAE
  &lt;chr&gt;                      &lt;chr&gt;                     &lt;dbl&gt;        &lt;dbl&gt; &lt;dbl&gt;
1 Full Model                 All Original Variables    0.622        0.578 8115.
2 OG Predictors with Log Age Log Age                   0.622        0.577 8127.
3 - Performance              PerformanceScore          0.622        0.580 8115.
4 - DaysLateLast30           Above + DaysLateLast30    0.622        0.582 8109.
5 Combined Managers          Above + ManagerName       0.608        0.582 8295.
6 - Married                  Above + Married           0.608        0.584 8291.
7 - Age                      Above + Age               0.608        0.585 8291.
8 - GenderCode               Above + Gender            0.607        0.587 8310.</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 5
  Model                      Pruned_Variables       R_Square Adj_R_Square   MAE
  &lt;chr&gt;                      &lt;chr&gt;                     &lt;dbl&gt;        &lt;dbl&gt; &lt;dbl&gt;
1 Full Model                 All Original Variables    0.622        0.578 8115.
2 OG Predictors with Log Age Log Age                   0.622        0.577 8127.
3 - Performance              PerformanceScore          0.622        0.580 8115.
4 - DaysLateLast30           Above + DaysLateLast30    0.622        0.582 8109.
5 Combined Managers          Above + ManagerName       0.608        0.582 8295.
6 - Married                  Above + Married           0.608        0.584 8291.
7 - Age                      Above + Age               0.608        0.585 8291.
8 - GenderCode               Above + Gender            0.607        0.587 8310.
9 - EmpStatus                Above + EmpStatus         0.605        0.587 8332.</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 5
   Model                      Pruned_Variables       R_Square Adj_R_Square   MAE
   &lt;chr&gt;                      &lt;chr&gt;                     &lt;dbl&gt;        &lt;dbl&gt; &lt;dbl&gt;
 1 Full Model                 All Original Variables    0.622        0.578 8115.
 2 OG Predictors with Log Age Log Age                   0.622        0.577 8127.
 3 - Performance              PerformanceScore          0.622        0.580 8115.
 4 - DaysLateLast30           Above + DaysLateLast30    0.622        0.582 8109.
 5 Combined Managers          Above + ManagerName       0.608        0.582 8295.
 6 - Married                  Above + Married           0.608        0.584 8291.
 7 - Age                      Above + Age               0.608        0.585 8291.
 8 - GenderCode               Above + Gender            0.607        0.587 8310.
 9 - EmpStatus                Above + EmpStatus         0.605        0.587 8332.
10 - Survey                   Above + Survey            0.604        0.588 8328.</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 11 × 5
   Model                      Pruned_Variables       R_Square Adj_R_Square   MAE
   &lt;chr&gt;                      &lt;chr&gt;                     &lt;dbl&gt;        &lt;dbl&gt; &lt;dbl&gt;
 1 Full Model                 All Original Variables    0.622        0.578 8115.
 2 OG Predictors with Log Age Log Age                   0.622        0.577 8127.
 3 - Performance              PerformanceScore          0.622        0.580 8115.
 4 - DaysLateLast30           Above + DaysLateLast30    0.622        0.582 8109.
 5 Combined Managers          Above + ManagerName       0.608        0.582 8295.
 6 - Married                  Above + Married           0.608        0.584 8291.
 7 - Age                      Above + Age               0.608        0.585 8291.
 8 - GenderCode               Above + Gender            0.607        0.587 8310.
 9 - EmpStatus                Above + EmpStatus         0.605        0.587 8332.
10 - Survey                   Above + Survey            0.604        0.588 8328.
11 - Absence                  Above + Absence           0.604        0.589 8361.</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 5
   Model                      Pruned_Variables       R_Square Adj_R_Square   MAE
   &lt;chr&gt;                      &lt;chr&gt;                     &lt;dbl&gt;        &lt;dbl&gt; &lt;dbl&gt;
 1 Full Model                 All Original Variables    0.622        0.578 8115.
 2 OG Predictors with Log Age Log Age                   0.622        0.577 8127.
 3 - Performance              PerformanceScore          0.622        0.580 8115.
 4 - DaysLateLast30           Above + DaysLateLast30    0.622        0.582 8109.
 5 Combined Managers          Above + ManagerName       0.608        0.582 8295.
 6 - Married                  Above + Married           0.608        0.584 8291.
 7 - Age                      Above + Age               0.608        0.585 8291.
 8 - GenderCode               Above + Gender            0.607        0.587 8310.
 9 - EmpStatus                Above + EmpStatus         0.605        0.587 8332.
10 - Survey                   Above + Survey            0.604        0.588 8328.
11 - Absence                  Above + Absence           0.604        0.589 8361.
12 - Satisfaction             Above + Satisfaction      0.603        0.589 8362.</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13 × 5
   Model                      Pruned_Variables       R_Square Adj_R_Square   MAE
   &lt;chr&gt;                      &lt;chr&gt;                     &lt;dbl&gt;        &lt;dbl&gt; &lt;dbl&gt;
 1 Full Model                 All Original Variables    0.622        0.578 8115.
 2 OG Predictors with Log Age Log Age                   0.622        0.577 8127.
 3 - Performance              PerformanceScore          0.622        0.580 8115.
 4 - DaysLateLast30           Above + DaysLateLast30    0.622        0.582 8109.
 5 Combined Managers          Above + ManagerName       0.608        0.582 8295.
 6 - Married                  Above + Married           0.608        0.584 8291.
 7 - Age                      Above + Age               0.608        0.585 8291.
 8 - GenderCode               Above + Gender            0.607        0.587 8310.
 9 - EmpStatus                Above + EmpStatus         0.605        0.587 8332.
10 - Survey                   Above + Survey            0.604        0.588 8328.
11 - Absence                  Above + Absence           0.604        0.589 8361.
12 - Satisfaction             Above + Satisfaction      0.603        0.589 8362.
13 - JobFair                  Above + Job Fair          0.601        0.588 8380.</code></pre>
</div>
</div>
<p>woah… adj rq went down by .001… let’s keep <code>FromDiversityJobFair</code> as a predictor for <code>Salary</code>. Our final model will be <code>- Satisfaction</code>. Let’s rename it and look at the predicted vs actual salary plot.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="HW1_Carlo_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="384"></p>
</figure>
</div>
</div>
</div>
<p>Let’s take a look again at our final results summary table and our full summary of the final model.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13 × 5
   Model                      Pruned_Variables       R_Square Adj_R_Square   MAE
   &lt;chr&gt;                      &lt;chr&gt;                     &lt;dbl&gt;        &lt;dbl&gt; &lt;dbl&gt;
 1 Full Model                 All Original Variables    0.622        0.578 8115.
 2 OG Predictors with Log Age Log Age                   0.622        0.577 8127.
 3 - Performance              PerformanceScore          0.622        0.580 8115.
 4 - DaysLateLast30           Above + DaysLateLast30    0.622        0.582 8109.
 5 Combined Managers          Above + ManagerName       0.608        0.582 8295.
 6 - Married                  Above + Married           0.608        0.584 8291.
 7 - Age                      Above + Age               0.608        0.585 8291.
 8 - GenderCode               Above + Gender            0.607        0.587 8310.
 9 - EmpStatus                Above + EmpStatus         0.605        0.587 8332.
10 - Survey                   Above + Survey            0.604        0.588 8328.
11 - Absence                  Above + Absence           0.604        0.589 8361.
12 - Satisfaction             Above + Satisfaction      0.603        0.589 8362.
13 - JobFair                  Above + Job Fair          0.601        0.588 8380.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
stats::lm(formula = Salary ~ . - age_log - PerformanceScore - 
    DaysLateLast30 - ManagerName - Married - Age - GenderCode - 
    Gender - EmploymentStatus - EngagementSurvey - Absences - 
    EmpSatisfaction, data = data)

Residuals:
   Min     1Q Median     3Q    Max 
-38982  -6457    509   5934  50552 

Coefficients: (1 not defined because of singularities)
                               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                     96207.4    12583.9   7.645 2.96e-13 ***
DeptID                          15267.6     2064.7   7.395 1.48e-12 ***
FromDiversityJobFairYes          3015.9     2399.2   1.257 0.209727    
SpecialProjectsCount            -2632.9     1240.3  -2.123 0.034608 *  
TimeEmployed                     -654.3      316.6  -2.067 0.039604 *  
DepartmentIT/IS                 12268.4     4087.1   3.002 0.002914 ** 
DepartmentProduction           -63132.0     8163.6  -7.733 1.67e-13 ***
DepartmentSales                -80516.1    10319.4  -7.802 1.06e-13 ***
DepartmentSoftware Engineering       NA         NA      NA       NA    
mgr_combJanet King             -33058.7    13112.2  -2.521 0.012222 *  
mgr_combJennifer Zamora        -30225.8    12901.9  -2.343 0.019808 *  
mgr_combOther                  -47849.3    13062.9  -3.663 0.000295 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 11870 on 295 degrees of freedom
Multiple R-squared:  0.6027,    Adjusted R-squared:  0.5893 
F-statistic: 44.76 on 10 and 295 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>We can see from the results table that these models did not change value for Mean Absolute Error (MAE). Also, the adjusted R squares are very close together. Looking at the final model fit summary, we can see that all predictors are significant (p&lt;0.5). The exception here is <code>FromDiversityJobFair</code> which has a p value of 0.209. We are keeping this because the adjusted r square value of the model decreases, albeit only by a hair, when removed.</p>
<p>Now I will test predictor interactions &amp; compare to all the models.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 43%">
<col style="width: 16%">
<col style="width: 15%">
<col style="width: 13%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">111741.2448</td>
<td style="text-align: right;">12567.0422</td>
<td style="text-align: right;">8.8916</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">SpecialProjectsCount</td>
<td style="text-align: right;">-2815.6299</td>
<td style="text-align: right;">1232.9726</td>
<td style="text-align: right;">-2.2836</td>
<td style="text-align: right;">0.0231</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TimeEmployed</td>
<td style="text-align: right;">-644.8689</td>
<td style="text-align: right;">316.7797</td>
<td style="text-align: right;">-2.0357</td>
<td style="text-align: right;">0.0427</td>
</tr>
<tr class="even">
<td style="text-align: left;">DepartmentIT/IS</td>
<td style="text-align: right;">42430.3011</td>
<td style="text-align: right;">5930.0399</td>
<td style="text-align: right;">7.1551</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">DepartmentProduction</td>
<td style="text-align: right;">-3492.1480</td>
<td style="text-align: right;">6153.3734</td>
<td style="text-align: right;">-0.5675</td>
<td style="text-align: right;">0.5708</td>
</tr>
<tr class="even">
<td style="text-align: left;">DepartmentSales</td>
<td style="text-align: right;">-5820.5540</td>
<td style="text-align: right;">6127.2331</td>
<td style="text-align: right;">-0.9499</td>
<td style="text-align: right;">0.3429</td>
</tr>
<tr class="odd">
<td style="text-align: left;">DepartmentSoftware Engineering</td>
<td style="text-align: right;">45529.8271</td>
<td style="text-align: right;">6196.2577</td>
<td style="text-align: right;">7.3480</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">mgr_combJanet King</td>
<td style="text-align: right;">-31662.7692</td>
<td style="text-align: right;">13077.9104</td>
<td style="text-align: right;">-2.4211</td>
<td style="text-align: right;">0.0161</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mgr_combJennifer Zamora</td>
<td style="text-align: right;">-28487.7551</td>
<td style="text-align: right;">12840.1972</td>
<td style="text-align: right;">-2.2186</td>
<td style="text-align: right;">0.0273</td>
</tr>
<tr class="even">
<td style="text-align: left;">mgr_combOther</td>
<td style="text-align: right;">-46487.5419</td>
<td style="text-align: right;">13030.6394</td>
<td style="text-align: right;">-3.5676</td>
<td style="text-align: right;">0.0004</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 14%">
<col style="width: 19%">
<col style="width: 12%">
<col style="width: 14%">
<col style="width: 11%">
<col style="width: 4%">
<col style="width: 16%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">r.squared</th>
<th style="text-align: right;">adj.r.squared</th>
<th style="text-align: right;">sigma</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">df.residual</th>
<th style="text-align: right;">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.6006</td>
<td style="text-align: right;">0.5885</td>
<td style="text-align: right;">11880.84</td>
<td style="text-align: right;">49.4584</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">296</td>
<td style="text-align: right;">306</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 14 × 5
   Model                      Pruned_Variables       R_Square Adj_R_Square   MAE
   &lt;chr&gt;                      &lt;chr&gt;                     &lt;dbl&gt;        &lt;dbl&gt; &lt;dbl&gt;
 1 Full Model                 All Original Variables    0.622        0.578 8115.
 2 OG Predictors with Log Age Log Age                   0.622        0.577 8127.
 3 - Performance              PerformanceScore          0.622        0.580 8115.
 4 - DaysLateLast30           Above + DaysLateLast30    0.622        0.582 8109.
 5 Combined Managers          Above + ManagerName       0.608        0.582 8295.
 6 - Married                  Above + Married           0.608        0.584 8291.
 7 - Age                      Above + Age               0.608        0.585 8291.
 8 - GenderCode               Above + Gender            0.607        0.587 8310.
 9 - EmpStatus                Above + EmpStatus         0.605        0.587 8332.
10 - Survey                   Above + Survey            0.604        0.588 8328.
11 - Absence                  Above + Absence           0.604        0.589 8361.
12 - Satisfaction             Above + Satisfaction      0.603        0.589 8362.
13 - JobFair                  Above + Job Fair          0.601        0.588 8380.
14 lm + interactions          Interactions              0.601        0.588 8380.</code></pre>
</div>
</div>
<p>From all of our model summary tables and residual plots, we can see that our final model is not that much better than our original model. Through this pruning process, we have kept the same MAE and increased our Adjusted R Squared by 0.01091.</p>
</section>
<section id="appendix" class="level2">
<h2 class="anchored" data-anchor-id="appendix">Appendix</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">fig.align=</span><span class="st">"center"</span>,</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">fig.height=</span><span class="fl">2.66</span>,</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">fig.width=</span><span class="dv">4</span>,</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">warning =</span> <span class="cn">FALSE</span>,</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>                      <span class="at">message =</span> <span class="cn">FALSE</span>,</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>                      <span class="at">comment =</span> <span class="cn">NA</span>,</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>                      <span class="at">echo=</span><span class="cn">FALSE</span>)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels) </span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="co">#library(parsnip) #v1.0.0 linear_reg(), set_engine(), set_mode(), fit(), predict()</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>  <span class="co">#library(yardstick) #v1.0.0 metrics()</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  <span class="co">#library(dplyr) #v1.0.9 %&gt;%, select(), select_if(), filter(), mutate(), group_by(), </span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>      <span class="co">#summarize(), tibble()</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>  <span class="co">#library(ggplot2) #v3.3.6 ggplot()</span></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>  <span class="co">#library(broom) #v0.8.0 for tidy(), augment(), glance()</span></span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr) <span class="co">#v1.39 kable and allows you to create Appendix with all_labels()</span></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr) <span class="co">#v2.1.2 read_csv()</span></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally) <span class="co">#v2.1.2 for ggpairs</span></span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance) <span class="co">#v0.9.1 check_model</span></span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(see) <span class="co">#v0.7.1  for check_model plots from performance</span></span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork) <span class="co">#v1.1.1for check_model plots from performance</span></span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr) <span class="co">#v2.1.4 for for skim()</span></span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest) <span class="co">#v0.9-40 bptest() (constant variance), dwtest() (indep)</span></span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(interactions) <span class="co">#v1.1.5 interaction_plot</span></span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggcorrplot) <span class="co">#v0.1.3 ggcorrplot()</span></span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plotly) <span class="co">#v4.10.1</span></span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_bw</span>()) <span class="co">#sets default ggplot output style</span></span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a>Manager <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Manager.csv"</span>)</span>
<span id="cb20-30"><a href="#cb20-30" aria-hidden="true" tabindex="-1"></a>PerfScore <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"PerfScore.csv"</span>)</span>
<span id="cb20-31"><a href="#cb20-31" aria-hidden="true" tabindex="-1"></a>HR <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">'HRDataset_23.csv'</span>)</span>
<span id="cb20-32"><a href="#cb20-32" aria-hidden="true" tabindex="-1"></a>EmpStatus <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"EmpStatus.csv"</span>)</span>
<span id="cb20-33"><a href="#cb20-33" aria-hidden="true" tabindex="-1"></a>Dept <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Dept.csv"</span>)</span>
<span id="cb20-34"><a href="#cb20-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-35"><a href="#cb20-35" aria-hidden="true" tabindex="-1"></a>HR <span class="ot">&lt;-</span> HR <span class="sc">%&gt;%</span> </span>
<span id="cb20-36"><a href="#cb20-36" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>Zip,<span class="sc">-</span>State,<span class="sc">-</span>TermReason, <span class="sc">-</span>Employee_Name)</span>
<span id="cb20-37"><a href="#cb20-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-38"><a href="#cb20-38" aria-hidden="true" tabindex="-1"></a><span class="co">#head(HR$DOB)</span></span>
<span id="cb20-39"><a href="#cb20-39" aria-hidden="true" tabindex="-1"></a><span class="co">#change DOB, DateofHire, &amp; DateofTermination to as.Date</span></span>
<span id="cb20-40"><a href="#cb20-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-41"><a href="#cb20-41" aria-hidden="true" tabindex="-1"></a>HR<span class="sc">$</span>DOB <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(HR<span class="sc">$</span>DOB, <span class="st">"%m/%d/%y"</span>)</span>
<span id="cb20-42"><a href="#cb20-42" aria-hidden="true" tabindex="-1"></a>HR<span class="sc">$</span>DateofHire <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(HR<span class="sc">$</span>DateofHire, <span class="st">"%m/%d/%y"</span>)</span>
<span id="cb20-43"><a href="#cb20-43" aria-hidden="true" tabindex="-1"></a>HR<span class="sc">$</span>DateofTermination <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(HR<span class="sc">$</span>DateofTermination, <span class="st">"%m/%d/%y"</span>)</span>
<span id="cb20-44"><a href="#cb20-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-45"><a href="#cb20-45" aria-hidden="true" tabindex="-1"></a><span class="co">#Age &amp; TimeEmployed</span></span>
<span id="cb20-46"><a href="#cb20-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-47"><a href="#cb20-47" aria-hidden="true" tabindex="-1"></a>HR <span class="ot">&lt;-</span>HR <span class="sc">%&gt;%</span> </span>
<span id="cb20-48"><a href="#cb20-48" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Age =</span> <span class="fu">as.numeric</span>(<span class="fu">difftime</span>(<span class="st">"2019-06-30"</span>,DateofHire, <span class="at">units=</span><span class="st">"days"</span>)<span class="sc">/</span><span class="fl">365.25</span>))</span>
<span id="cb20-49"><a href="#cb20-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-50"><a href="#cb20-50" aria-hidden="true" tabindex="-1"></a>HR <span class="ot">&lt;-</span> HR <span class="sc">%&gt;%</span> </span>
<span id="cb20-51"><a href="#cb20-51" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">TimeEmployed =</span> <span class="fu">if_else</span>(<span class="fu">is.na</span>(DateofTermination),</span>
<span id="cb20-52"><a href="#cb20-52" aria-hidden="true" tabindex="-1"></a>    <span class="fu">as.numeric</span>(<span class="fu">difftime</span>(<span class="st">"2019-06-30"</span>, DateofHire, <span class="at">units =</span> <span class="st">"days"</span>) <span class="sc">/</span> <span class="fl">365.25</span>),</span>
<span id="cb20-53"><a href="#cb20-53" aria-hidden="true" tabindex="-1"></a>    <span class="fu">as.numeric</span>(<span class="fu">difftime</span>(DateofTermination, DateofHire, <span class="at">units =</span> <span class="st">"days"</span>) <span class="sc">/</span> <span class="fl">365.25</span>)))</span>
<span id="cb20-54"><a href="#cb20-54" aria-hidden="true" tabindex="-1"></a><span class="co"># removing DOB, DateofHire, DateofTermination</span></span>
<span id="cb20-55"><a href="#cb20-55" aria-hidden="true" tabindex="-1"></a>HR<span class="ot">&lt;-</span> HR <span class="sc">%&gt;%</span> </span>
<span id="cb20-56"><a href="#cb20-56" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>DOB,<span class="sc">-</span>DateofHire,<span class="sc">-</span>DateofTermination)</span>
<span id="cb20-57"><a href="#cb20-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-58"><a href="#cb20-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-59"><a href="#cb20-59" aria-hidden="true" tabindex="-1"></a>df_original <span class="ot">&lt;-</span> HR <span class="sc">%&gt;%</span> </span>
<span id="cb20-60"><a href="#cb20-60" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(Manager) <span class="sc">%&gt;%</span> </span>
<span id="cb20-61"><a href="#cb20-61" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(PerfScore) <span class="sc">%&gt;%</span> </span>
<span id="cb20-62"><a href="#cb20-62" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(Dept) <span class="sc">%&gt;%</span> </span>
<span id="cb20-63"><a href="#cb20-63" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(EmpStatus)</span>
<span id="cb20-64"><a href="#cb20-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-65"><a href="#cb20-65" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df_original)</span>
<span id="cb20-66"><a href="#cb20-66" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(df_original)</span>
<span id="cb20-67"><a href="#cb20-67" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df_original)</span>
<span id="cb20-68"><a href="#cb20-68" aria-hidden="true" tabindex="-1"></a>df_original <span class="ot">&lt;-</span> df_original <span class="sc">%&gt;%</span> </span>
<span id="cb20-69"><a href="#cb20-69" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>EmpStatusID,<span class="sc">-</span>ManagerID,<span class="sc">-</span>PerfScoreID,<span class="sc">-</span>EmpID)</span>
<span id="cb20-70"><a href="#cb20-70" aria-hidden="true" tabindex="-1"></a><span class="co">#Remove the rows of data for the Directors/CIO by excluding anyone who has a salary &gt;= $170K</span></span>
<span id="cb20-71"><a href="#cb20-71" aria-hidden="true" tabindex="-1"></a><span class="co">#(this should be 5 employees)</span></span>
<span id="cb20-72"><a href="#cb20-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-73"><a href="#cb20-73" aria-hidden="true" tabindex="-1"></a>df_original <span class="ot">&lt;-</span> df_original <span class="sc">%&gt;%</span>  </span>
<span id="cb20-74"><a href="#cb20-74" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Salary<span class="sc">&lt;</span><span class="dv">170000</span>)</span>
<span id="cb20-75"><a href="#cb20-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-76"><a href="#cb20-76" aria-hidden="true" tabindex="-1"></a><span class="co">#not using termd bc duplicated in emplotment status</span></span>
<span id="cb20-77"><a href="#cb20-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-78"><a href="#cb20-78" aria-hidden="true" tabindex="-1"></a>df_original <span class="ot">&lt;-</span> df_original <span class="sc">%&gt;%</span> </span>
<span id="cb20-79"><a href="#cb20-79" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>Termd)</span>
<span id="cb20-80"><a href="#cb20-80" aria-hidden="true" tabindex="-1"></a>df_original <span class="ot">&lt;-</span> df_original <span class="sc">%&gt;%</span> </span>
<span id="cb20-81"><a href="#cb20-81" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">PerformanceScore =</span> <span class="fu">if_else</span>(PerformanceScore <span class="sc">%in%</span> </span>
<span id="cb20-82"><a href="#cb20-82" aria-hidden="true" tabindex="-1"></a>                                      <span class="fu">c</span>(<span class="st">'Needs Improvement'</span>, <span class="st">'PIP'</span>), </span>
<span id="cb20-83"><a href="#cb20-83" aria-hidden="true" tabindex="-1"></a>                                    <span class="st">'Improvement'</span>, PerformanceScore))</span>
<span id="cb20-84"><a href="#cb20-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-85"><a href="#cb20-85" aria-hidden="true" tabindex="-1"></a>df_original <span class="ot">&lt;-</span> df_original <span class="sc">%&gt;%</span> </span>
<span id="cb20-86"><a href="#cb20-86" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Married =</span> <span class="fu">if_else</span>(Married<span class="sc">==</span><span class="dv">1</span>,<span class="st">"Yes"</span>,<span class="st">"No"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb20-87"><a href="#cb20-87" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">FromDiversityJobFair =</span> <span class="fu">if_else</span>(FromDiversityJobFair<span class="sc">==</span><span class="dv">1</span>, <span class="st">"Yes"</span>,<span class="st">'No'</span>))</span>
<span id="cb20-88"><a href="#cb20-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-89"><a href="#cb20-89" aria-hidden="true" tabindex="-1"></a>df_original <span class="ot">&lt;-</span> df_original <span class="sc">%&gt;%</span> </span>
<span id="cb20-90"><a href="#cb20-90" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Gender =</span> <span class="fu">if_else</span>(GenderCode<span class="sc">==</span><span class="dv">1</span>,<span class="st">"Male"</span>,<span class="fu">if_else</span>(GenderCode<span class="sc">==</span><span class="dv">2</span>,<span class="st">"Female"</span>,<span class="st">"Other"</span>)))</span>
<span id="cb20-91"><a href="#cb20-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-92"><a href="#cb20-92" aria-hidden="true" tabindex="-1"></a><span class="co">#making sure datatypes are correct</span></span>
<span id="cb20-93"><a href="#cb20-93" aria-hidden="true" tabindex="-1"></a>df_original <span class="ot">&lt;-</span> df_original <span class="sc">%&gt;%</span> </span>
<span id="cb20-94"><a href="#cb20-94" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.character),as.factor))</span>
<span id="cb20-95"><a href="#cb20-95" aria-hidden="true" tabindex="-1"></a>df_num <span class="ot">&lt;-</span> <span class="fu">select_if</span>(df_original,is.numeric)</span>
<span id="cb20-96"><a href="#cb20-96" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(predictor <span class="cf">in</span> <span class="fu">colnames</span>(df_num)) {</span>
<span id="cb20-97"><a href="#cb20-97" aria-hidden="true" tabindex="-1"></a>  predictor_mean <span class="ot">&lt;-</span><span class="fu">mean</span>(df_num[[predictor]],<span class="at">na.rm=</span><span class="cn">TRUE</span>) <span class="co"># mean</span></span>
<span id="cb20-98"><a href="#cb20-98" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df_num,</span>
<span id="cb20-99"><a href="#cb20-99" aria-hidden="true" tabindex="-1"></a>              <span class="fu">aes</span>(<span class="at">x=</span>.data[[predictor]])) <span class="sc">+</span></span>
<span id="cb20-100"><a href="#cb20-100" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_histogram</span>() <span class="sc">+</span> </span>
<span id="cb20-101"><a href="#cb20-101" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="fu">paste</span>(<span class="st">"Histogram for"</span>, predictor, <span class="st">"(Mean ="</span>,predictor_mean,<span class="st">")"</span>))</span>
<span id="cb20-102"><a href="#cb20-102" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb20-103"><a href="#cb20-103" aria-hidden="true" tabindex="-1"></a>  p<span class="ot">&lt;-</span><span class="fu">ggplotly</span>(p)</span>
<span id="cb20-104"><a href="#cb20-104" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb20-105"><a href="#cb20-105" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(p)</span>
<span id="cb20-106"><a href="#cb20-106" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb20-107"><a href="#cb20-107" aria-hidden="true" tabindex="-1"></a><span class="co">#Age was skewed right transforming</span></span>
<span id="cb20-108"><a href="#cb20-108" aria-hidden="true" tabindex="-1"></a>df_original <span class="ot">&lt;-</span> df_original <span class="sc">%&gt;%</span> </span>
<span id="cb20-109"><a href="#cb20-109" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">age_log =</span> <span class="fu">log</span>(Age))</span>
<span id="cb20-110"><a href="#cb20-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-111"><a href="#cb20-111" aria-hidden="true" tabindex="-1"></a>df_fac <span class="ot">&lt;-</span> <span class="fu">select_if</span>(df_original,is.factor)</span>
<span id="cb20-112"><a href="#cb20-112" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (variable <span class="cf">in</span> <span class="fu">colnames</span>(df_fac)) {</span>
<span id="cb20-113"><a href="#cb20-113" aria-hidden="true" tabindex="-1"></a>  sum_table <span class="ot">&lt;-</span> df_fac <span class="sc">%&gt;%</span> </span>
<span id="cb20-114"><a href="#cb20-114" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(.data[[variable]]) <span class="sc">%&gt;%</span> </span>
<span id="cb20-115"><a href="#cb20-115" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">count=</span><span class="fu">n</span>())</span>
<span id="cb20-116"><a href="#cb20-116" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb20-117"><a href="#cb20-117" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(sum_table,<span class="fu">aes</span>(<span class="at">x=</span>.data[[variable]],</span>
<span id="cb20-118"><a href="#cb20-118" aria-hidden="true" tabindex="-1"></a>                            <span class="at">y=</span>count)) <span class="sc">+</span></span>
<span id="cb20-119"><a href="#cb20-119" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_bar</span>(<span class="at">stat=</span><span class="st">"identity"</span>) <span class="sc">+</span> </span>
<span id="cb20-120"><a href="#cb20-120" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> count), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb20-121"><a href="#cb20-121" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x=</span> variable, <span class="at">y=</span><span class="st">"count"</span>) <span class="sc">+</span></span>
<span id="cb20-122"><a href="#cb20-122" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="fu">paste</span>(<span class="st">"Count of"</span>, variable))</span>
<span id="cb20-123"><a href="#cb20-123" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb20-124"><a href="#cb20-124" aria-hidden="true" tabindex="-1"></a>  p<span class="ot">&lt;-</span><span class="fu">ggplotly</span>(p)</span>
<span id="cb20-125"><a href="#cb20-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-126"><a href="#cb20-126" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(p)</span>
<span id="cb20-127"><a href="#cb20-127" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb20-128"><a href="#cb20-128" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb20-129"><a href="#cb20-129" aria-hidden="true" tabindex="-1"></a>df_original <span class="sc">%&gt;%</span> </span>
<span id="cb20-130"><a href="#cb20-130" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggpairs</span>()</span>
<span id="cb20-131"><a href="#cb20-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-132"><a href="#cb20-132" aria-hidden="true" tabindex="-1"></a><span class="co">#first model, full (without Age Log)</span></span>
<span id="cb20-133"><a href="#cb20-133" aria-hidden="true" tabindex="-1"></a>reg_spec <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span> <span class="do">## Class of problem</span></span>
<span id="cb20-134"><a href="#cb20-134" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">%&gt;%</span> <span class="do">## The particular function that we use</span></span>
<span id="cb20-135"><a href="#cb20-135" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">"regression"</span>) </span>
<span id="cb20-136"><a href="#cb20-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-137"><a href="#cb20-137" aria-hidden="true" tabindex="-1"></a>reg_full_fit <span class="ot">&lt;-</span> reg_spec <span class="sc">%&gt;%</span></span>
<span id="cb20-138"><a href="#cb20-138" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(Salary <span class="sc">~</span> .<span class="sc">-</span>age_log, </span>
<span id="cb20-139"><a href="#cb20-139" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> df_original)</span>
<span id="cb20-140"><a href="#cb20-140" aria-hidden="true" tabindex="-1"></a><span class="co">#full summary</span></span>
<span id="cb20-141"><a href="#cb20-141" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg_full_fit<span class="sc">$</span>fit)</span>
<span id="cb20-142"><a href="#cb20-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-143"><a href="#cb20-143" aria-hidden="true" tabindex="-1"></a>glance_full <span class="ot">&lt;-</span> <span class="fu">glance</span>(<span class="fu">summary</span>(reg_full_fit<span class="sc">$</span>fit))<span class="sc">%&gt;%</span> </span>
<span id="cb20-144"><a href="#cb20-144" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span> () </span>
<span id="cb20-145"><a href="#cb20-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-146"><a href="#cb20-146" aria-hidden="true" tabindex="-1"></a>glance_full <span class="sc">%&gt;%</span> </span>
<span id="cb20-147"><a href="#cb20-147" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">4</span>)</span>
<span id="cb20-148"><a href="#cb20-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-149"><a href="#cb20-149" aria-hidden="true" tabindex="-1"></a>mae <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">mean</span>(<span class="fu">abs</span>(reg_full_fit<span class="sc">$</span>fit<span class="sc">$</span>residual)))</span>
<span id="cb20-150"><a href="#cb20-150" aria-hidden="true" tabindex="-1"></a>results_table <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">Model =</span> <span class="st">'Full Model'</span>,</span>
<span id="cb20-151"><a href="#cb20-151" aria-hidden="true" tabindex="-1"></a>                        <span class="at">Pruned_Variables =</span> <span class="st">"All Original Variables"</span>,</span>
<span id="cb20-152"><a href="#cb20-152" aria-hidden="true" tabindex="-1"></a>                        <span class="at">R_Square =</span> glance_full<span class="sc">$</span>r.squared,</span>
<span id="cb20-153"><a href="#cb20-153" aria-hidden="true" tabindex="-1"></a>                        <span class="at">Adj_R_Square =</span> glance_full<span class="sc">$</span>adj.r.squared,</span>
<span id="cb20-154"><a href="#cb20-154" aria-hidden="true" tabindex="-1"></a>                        <span class="at">MAE =</span> mae)</span>
<span id="cb20-155"><a href="#cb20-155" aria-hidden="true" tabindex="-1"></a>results_table</span>
<span id="cb20-156"><a href="#cb20-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-157"><a href="#cb20-157" aria-hidden="true" tabindex="-1"></a>pred_reg_full_fit <span class="ot">&lt;-</span> reg_full_fit<span class="sc">$</span>fit <span class="sc">%&gt;%</span></span>
<span id="cb20-158"><a href="#cb20-158" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(df_original) </span>
<span id="cb20-159"><a href="#cb20-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-160"><a href="#cb20-160" aria-hidden="true" tabindex="-1"></a><span class="co">#Reminder - if augment with $fit use y=.fitted</span></span>
<span id="cb20-161"><a href="#cb20-161" aria-hidden="true" tabindex="-1"></a><span class="co">#otherwise use .pred (look in object to see which)</span></span>
<span id="cb20-162"><a href="#cb20-162" aria-hidden="true" tabindex="-1"></a>pred_reg_full_fit <span class="sc">%&gt;%</span></span>
<span id="cb20-163"><a href="#cb20-163" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> .fitted, <span class="at">x =</span> Salary)) <span class="sc">+</span> </span>
<span id="cb20-164"><a href="#cb20-164" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">col =</span> <span class="st">"Blue"</span>) <span class="sc">+</span></span>
<span id="cb20-165"><a href="#cb20-165" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">col =</span> <span class="st">"Green"</span>) <span class="sc">+</span> </span>
<span id="cb20-166"><a href="#cb20-166" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Predicted vs Actual Salary for Initial (Full) Model"</span>,</span>
<span id="cb20-167"><a href="#cb20-167" aria-hidden="true" tabindex="-1"></a>          <span class="at">subtitle=</span><span class="fu">paste</span>(<span class="st">"Adj R-Squared:"</span>,</span>
<span id="cb20-168"><a href="#cb20-168" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">round</span>(<span class="fu">glance</span>(reg_full_fit)<span class="sc">$</span>adj.r.squared,<span class="dv">4</span>),</span>
<span id="cb20-169"><a href="#cb20-169" aria-hidden="true" tabindex="-1"></a>                         <span class="st">"  Mean Abs Residuals:"</span>,</span>
<span id="cb20-170"><a href="#cb20-170" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">round</span>(<span class="fu">mean</span>(<span class="fu">abs</span>(pred_reg_full_fit<span class="sc">$</span>.resid)),<span class="dv">4</span>)))</span>
<span id="cb20-171"><a href="#cb20-171" aria-hidden="true" tabindex="-1"></a><span class="co"># with age log instead of age</span></span>
<span id="cb20-172"><a href="#cb20-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-173"><a href="#cb20-173" aria-hidden="true" tabindex="-1"></a>reg_age_log_fit <span class="ot">&lt;-</span> reg_spec <span class="sc">%&gt;%</span></span>
<span id="cb20-174"><a href="#cb20-174" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(Salary <span class="sc">~</span> .<span class="sc">-</span>Age, </span>
<span id="cb20-175"><a href="#cb20-175" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> df_original)</span>
<span id="cb20-176"><a href="#cb20-176" aria-hidden="true" tabindex="-1"></a>mae <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">mean</span>(<span class="fu">abs</span>(reg_age_log_fit<span class="sc">$</span>fit<span class="sc">$</span>residual)))</span>
<span id="cb20-177"><a href="#cb20-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-178"><a href="#cb20-178" aria-hidden="true" tabindex="-1"></a>glance_age_log <span class="ot">&lt;-</span> <span class="fu">glance</span>(<span class="fu">summary</span>(reg_age_log_fit<span class="sc">$</span>fit)) </span>
<span id="cb20-179"><a href="#cb20-179" aria-hidden="true" tabindex="-1"></a><span class="co"># Adding to the summary table</span></span>
<span id="cb20-180"><a href="#cb20-180" aria-hidden="true" tabindex="-1"></a>results_curr <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">Model =</span> <span class="st">'OG Predictors with Log Age'</span>,</span>
<span id="cb20-181"><a href="#cb20-181" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Pruned_Variables =</span> <span class="st">"Log Age"</span>,</span>
<span id="cb20-182"><a href="#cb20-182" aria-hidden="true" tabindex="-1"></a>                              <span class="at">R_Square =</span> glance_age_log<span class="sc">$</span>r.squared,</span>
<span id="cb20-183"><a href="#cb20-183" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Adj_R_Square =</span> glance_age_log<span class="sc">$</span>adj.r.squared,</span>
<span id="cb20-184"><a href="#cb20-184" aria-hidden="true" tabindex="-1"></a>                              <span class="at">MAE =</span> mae)</span>
<span id="cb20-185"><a href="#cb20-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-186"><a href="#cb20-186" aria-hidden="true" tabindex="-1"></a>results_table <span class="ot">&lt;-</span>results_table <span class="sc">%&gt;%</span>  <span class="fu">bind_rows</span>(results_curr)</span>
<span id="cb20-187"><a href="#cb20-187" aria-hidden="true" tabindex="-1"></a>results_table</span>
<span id="cb20-188"><a href="#cb20-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-189"><a href="#cb20-189" aria-hidden="true" tabindex="-1"></a>reg_performance_fit <span class="ot">&lt;-</span> reg_spec <span class="sc">%&gt;%</span></span>
<span id="cb20-190"><a href="#cb20-190" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(Salary <span class="sc">~</span> .<span class="sc">-</span>age_log<span class="sc">-</span>PerformanceScore, </span>
<span id="cb20-191"><a href="#cb20-191" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> df_original)</span>
<span id="cb20-192"><a href="#cb20-192" aria-hidden="true" tabindex="-1"></a>mae <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">mean</span>(<span class="fu">abs</span>(reg_performance_fit<span class="sc">$</span>fit<span class="sc">$</span>residual)))</span>
<span id="cb20-193"><a href="#cb20-193" aria-hidden="true" tabindex="-1"></a>glance_performance <span class="ot">&lt;-</span> <span class="fu">glance</span>(<span class="fu">summary</span>(reg_performance_fit<span class="sc">$</span>fit)) </span>
<span id="cb20-194"><a href="#cb20-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-195"><a href="#cb20-195" aria-hidden="true" tabindex="-1"></a>results_curr <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">Model =</span> <span class="st">'- Performance'</span>,</span>
<span id="cb20-196"><a href="#cb20-196" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Pruned_Variables =</span> <span class="st">"PerformanceScore"</span>, <span class="co">#Age is not Log</span></span>
<span id="cb20-197"><a href="#cb20-197" aria-hidden="true" tabindex="-1"></a>                              <span class="at">R_Square =</span> glance_performance<span class="sc">$</span>r.squared,</span>
<span id="cb20-198"><a href="#cb20-198" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Adj_R_Square =</span> glance_performance<span class="sc">$</span>adj.r.squared,</span>
<span id="cb20-199"><a href="#cb20-199" aria-hidden="true" tabindex="-1"></a>                              <span class="at">MAE =</span> mae)</span>
<span id="cb20-200"><a href="#cb20-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-201"><a href="#cb20-201" aria-hidden="true" tabindex="-1"></a>results_table <span class="ot">&lt;-</span>results_table <span class="sc">%&gt;%</span>  <span class="fu">bind_rows</span>(results_curr)</span>
<span id="cb20-202"><a href="#cb20-202" aria-hidden="true" tabindex="-1"></a>results_table</span>
<span id="cb20-203"><a href="#cb20-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-204"><a href="#cb20-204" aria-hidden="true" tabindex="-1"></a><span class="co">#DaysLateLast30                             </span></span>
<span id="cb20-205"><a href="#cb20-205" aria-hidden="true" tabindex="-1"></a>reg_late_fit <span class="ot">&lt;-</span> reg_spec <span class="sc">%&gt;%</span></span>
<span id="cb20-206"><a href="#cb20-206" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(Salary <span class="sc">~</span> .<span class="sc">-</span>age_log<span class="sc">-</span>PerformanceScore<span class="sc">-</span>DaysLateLast30 , </span>
<span id="cb20-207"><a href="#cb20-207" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> df_original)</span>
<span id="cb20-208"><a href="#cb20-208" aria-hidden="true" tabindex="-1"></a>mae <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">mean</span>(<span class="fu">abs</span>(reg_late_fit<span class="sc">$</span>fit<span class="sc">$</span>residual)))</span>
<span id="cb20-209"><a href="#cb20-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-210"><a href="#cb20-210" aria-hidden="true" tabindex="-1"></a>glance_late <span class="ot">&lt;-</span> <span class="fu">glance</span>(<span class="fu">summary</span>(reg_late_fit<span class="sc">$</span>fit))</span>
<span id="cb20-211"><a href="#cb20-211" aria-hidden="true" tabindex="-1"></a>results_curr <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">Model =</span> <span class="st">'- DaysLateLast30'</span>,</span>
<span id="cb20-212"><a href="#cb20-212" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Pruned_Variables =</span> <span class="st">"Above + DaysLateLast30"</span>, <span class="co">#Age is not Log</span></span>
<span id="cb20-213"><a href="#cb20-213" aria-hidden="true" tabindex="-1"></a>                              <span class="at">R_Square =</span> glance_late<span class="sc">$</span>r.squared,</span>
<span id="cb20-214"><a href="#cb20-214" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Adj_R_Square =</span> glance_late<span class="sc">$</span>adj.r.squared,</span>
<span id="cb20-215"><a href="#cb20-215" aria-hidden="true" tabindex="-1"></a>                              <span class="at">MAE =</span> mae)</span>
<span id="cb20-216"><a href="#cb20-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-217"><a href="#cb20-217" aria-hidden="true" tabindex="-1"></a>results_table <span class="ot">&lt;-</span>results_table <span class="sc">%&gt;%</span>  <span class="fu">bind_rows</span>(results_curr)</span>
<span id="cb20-218"><a href="#cb20-218" aria-hidden="true" tabindex="-1"></a>results_table</span>
<span id="cb20-219"><a href="#cb20-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-220"><a href="#cb20-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-221"><a href="#cb20-221" aria-hidden="true" tabindex="-1"></a>df_original <span class="ot">&lt;-</span> df_original <span class="sc">%&gt;%</span> </span>
<span id="cb20-222"><a href="#cb20-222" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">mgr_comb=</span><span class="fu">ifelse</span>(ManagerName<span class="sc">==</span><span class="st">"Janet King"</span>,<span class="st">"Janet King"</span>,</span>
<span id="cb20-223"><a href="#cb20-223" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">ifelse</span>(ManagerName<span class="sc">==</span><span class="st">'Jennifer Zamora'</span>,<span class="st">'Jennifer Zamora'</span>,</span>
<span id="cb20-224"><a href="#cb20-224" aria-hidden="true" tabindex="-1"></a>                                <span class="fu">ifelse</span>(ManagerName<span class="sc">==</span><span class="st">'Board of Directors'</span>,</span>
<span id="cb20-225"><a href="#cb20-225" aria-hidden="true" tabindex="-1"></a>                                       <span class="st">'Board of Directors'</span>,<span class="st">'Other'</span>))))  </span>
<span id="cb20-226"><a href="#cb20-226" aria-hidden="true" tabindex="-1"></a>reg_mgr_fit <span class="ot">&lt;-</span> reg_spec <span class="sc">%&gt;%</span> </span>
<span id="cb20-227"><a href="#cb20-227" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(Salary <span class="sc">~</span> .<span class="sc">-</span>age_log<span class="sc">-</span>PerformanceScore<span class="sc">-</span>DaysLateLast30<span class="sc">-</span>ManagerName, </span>
<span id="cb20-228"><a href="#cb20-228" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> df_original)</span>
<span id="cb20-229"><a href="#cb20-229" aria-hidden="true" tabindex="-1"></a>mae <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">mean</span>(<span class="fu">abs</span>(reg_mgr_fit<span class="sc">$</span>fit<span class="sc">$</span>residual)))</span>
<span id="cb20-230"><a href="#cb20-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-231"><a href="#cb20-231" aria-hidden="true" tabindex="-1"></a>glance_manager <span class="ot">&lt;-</span> <span class="fu">glance</span>(<span class="fu">summary</span>(reg_mgr_fit<span class="sc">$</span>fit)) </span>
<span id="cb20-232"><a href="#cb20-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-233"><a href="#cb20-233" aria-hidden="true" tabindex="-1"></a>results_curr <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">Model =</span> <span class="st">'Combined Managers'</span>,</span>
<span id="cb20-234"><a href="#cb20-234" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Pruned_Variables =</span> <span class="st">"Above + ManagerName"</span>, <span class="co">#Age is not Log</span></span>
<span id="cb20-235"><a href="#cb20-235" aria-hidden="true" tabindex="-1"></a>                              <span class="at">R_Square =</span> glance_manager<span class="sc">$</span>r.squared,</span>
<span id="cb20-236"><a href="#cb20-236" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Adj_R_Square =</span> glance_manager<span class="sc">$</span>adj.r.squared,</span>
<span id="cb20-237"><a href="#cb20-237" aria-hidden="true" tabindex="-1"></a>                              <span class="at">MAE =</span> mae)</span>
<span id="cb20-238"><a href="#cb20-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-239"><a href="#cb20-239" aria-hidden="true" tabindex="-1"></a>results_table <span class="ot">&lt;-</span>results_table <span class="sc">%&gt;%</span>  <span class="fu">bind_rows</span>(results_curr)</span>
<span id="cb20-240"><a href="#cb20-240" aria-hidden="true" tabindex="-1"></a>results_table</span>
<span id="cb20-241"><a href="#cb20-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-242"><a href="#cb20-242" aria-hidden="true" tabindex="-1"></a>reg_marr_fit <span class="ot">&lt;-</span> reg_spec <span class="sc">%&gt;%</span> </span>
<span id="cb20-243"><a href="#cb20-243" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(Salary <span class="sc">~</span> .<span class="sc">-</span>age_log<span class="sc">-</span>PerformanceScore<span class="sc">-</span>DaysLateLast30<span class="sc">-</span>ManagerName<span class="sc">-</span>Married, </span>
<span id="cb20-244"><a href="#cb20-244" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> df_original)</span>
<span id="cb20-245"><a href="#cb20-245" aria-hidden="true" tabindex="-1"></a>mae <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">mean</span>(<span class="fu">abs</span>(reg_marr_fit<span class="sc">$</span>fit<span class="sc">$</span>residual)))</span>
<span id="cb20-246"><a href="#cb20-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-247"><a href="#cb20-247" aria-hidden="true" tabindex="-1"></a>glance_marriage <span class="ot">&lt;-</span> <span class="fu">glance</span>(<span class="fu">summary</span>(reg_marr_fit<span class="sc">$</span>fit)) </span>
<span id="cb20-248"><a href="#cb20-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-249"><a href="#cb20-249" aria-hidden="true" tabindex="-1"></a>results_curr <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">Model =</span> <span class="st">'- Married'</span>,</span>
<span id="cb20-250"><a href="#cb20-250" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Pruned_Variables =</span> <span class="st">"Above + Married"</span>, <span class="co">#Age is not Log</span></span>
<span id="cb20-251"><a href="#cb20-251" aria-hidden="true" tabindex="-1"></a>                              <span class="at">R_Square =</span> glance_marriage<span class="sc">$</span>r.squared,</span>
<span id="cb20-252"><a href="#cb20-252" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Adj_R_Square =</span> glance_marriage<span class="sc">$</span>adj.r.squared,</span>
<span id="cb20-253"><a href="#cb20-253" aria-hidden="true" tabindex="-1"></a>                              <span class="at">MAE =</span> mae)</span>
<span id="cb20-254"><a href="#cb20-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-255"><a href="#cb20-255" aria-hidden="true" tabindex="-1"></a>results_table <span class="ot">&lt;-</span>results_table <span class="sc">%&gt;%</span>  <span class="fu">bind_rows</span>(results_curr)</span>
<span id="cb20-256"><a href="#cb20-256" aria-hidden="true" tabindex="-1"></a>results_table</span>
<span id="cb20-257"><a href="#cb20-257" aria-hidden="true" tabindex="-1"></a>reg_Age_fit <span class="ot">&lt;-</span> reg_spec <span class="sc">%&gt;%</span> </span>
<span id="cb20-258"><a href="#cb20-258" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(Salary <span class="sc">~</span> .<span class="sc">-</span>age_log<span class="sc">-</span>PerformanceScore<span class="sc">-</span>DaysLateLast30<span class="sc">-</span>ManagerName<span class="sc">-</span>Married<span class="sc">-</span>Age, </span>
<span id="cb20-259"><a href="#cb20-259" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> df_original)</span>
<span id="cb20-260"><a href="#cb20-260" aria-hidden="true" tabindex="-1"></a>mae <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">mean</span>(<span class="fu">abs</span>(reg_marr_fit<span class="sc">$</span>fit<span class="sc">$</span>residual)))</span>
<span id="cb20-261"><a href="#cb20-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-262"><a href="#cb20-262" aria-hidden="true" tabindex="-1"></a>glance_age <span class="ot">&lt;-</span> <span class="fu">glance</span>(<span class="fu">summary</span>(reg_Age_fit<span class="sc">$</span>fit)) </span>
<span id="cb20-263"><a href="#cb20-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-264"><a href="#cb20-264" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-265"><a href="#cb20-265" aria-hidden="true" tabindex="-1"></a>results_curr <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">Model =</span> <span class="st">'- Age'</span>,</span>
<span id="cb20-266"><a href="#cb20-266" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Pruned_Variables =</span> <span class="st">"Above + Age"</span>,</span>
<span id="cb20-267"><a href="#cb20-267" aria-hidden="true" tabindex="-1"></a>                              <span class="at">R_Square =</span> glance_age<span class="sc">$</span>r.squared,</span>
<span id="cb20-268"><a href="#cb20-268" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Adj_R_Square =</span> glance_age<span class="sc">$</span>adj.r.squared,</span>
<span id="cb20-269"><a href="#cb20-269" aria-hidden="true" tabindex="-1"></a>                              <span class="at">MAE =</span> mae)</span>
<span id="cb20-270"><a href="#cb20-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-271"><a href="#cb20-271" aria-hidden="true" tabindex="-1"></a>results_table <span class="ot">&lt;-</span>results_table <span class="sc">%&gt;%</span>  <span class="fu">bind_rows</span>(results_curr)</span>
<span id="cb20-272"><a href="#cb20-272" aria-hidden="true" tabindex="-1"></a>results_table</span>
<span id="cb20-273"><a href="#cb20-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-274"><a href="#cb20-274" aria-hidden="true" tabindex="-1"></a>reg_Gen_fit <span class="ot">&lt;-</span> reg_spec <span class="sc">%&gt;%</span> </span>
<span id="cb20-275"><a href="#cb20-275" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(Salary <span class="sc">~</span> .<span class="sc">-</span>age_log<span class="sc">-</span>PerformanceScore<span class="sc">-</span>DaysLateLast30<span class="sc">-</span>ManagerName<span class="sc">-</span>Married<span class="sc">-</span>Age<span class="sc">-</span>GenderCode<span class="sc">-</span>Gender, </span>
<span id="cb20-276"><a href="#cb20-276" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> df_original)</span>
<span id="cb20-277"><a href="#cb20-277" aria-hidden="true" tabindex="-1"></a>mae <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">mean</span>(<span class="fu">abs</span>(reg_Gen_fit<span class="sc">$</span>fit<span class="sc">$</span>residual)))</span>
<span id="cb20-278"><a href="#cb20-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-279"><a href="#cb20-279" aria-hidden="true" tabindex="-1"></a>glance_gender <span class="ot">&lt;-</span> <span class="fu">glance</span>(<span class="fu">summary</span>(reg_Gen_fit<span class="sc">$</span>fit)) </span>
<span id="cb20-280"><a href="#cb20-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-281"><a href="#cb20-281" aria-hidden="true" tabindex="-1"></a>results_curr <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">Model =</span> <span class="st">'- GenderCode'</span>,</span>
<span id="cb20-282"><a href="#cb20-282" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Pruned_Variables =</span> <span class="st">"Above + Gender"</span>,</span>
<span id="cb20-283"><a href="#cb20-283" aria-hidden="true" tabindex="-1"></a>                              <span class="at">R_Square =</span> glance_gender<span class="sc">$</span>r.squared,</span>
<span id="cb20-284"><a href="#cb20-284" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Adj_R_Square =</span> glance_gender<span class="sc">$</span>adj.r.squared,</span>
<span id="cb20-285"><a href="#cb20-285" aria-hidden="true" tabindex="-1"></a>                              <span class="at">MAE =</span> mae)</span>
<span id="cb20-286"><a href="#cb20-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-287"><a href="#cb20-287" aria-hidden="true" tabindex="-1"></a>results_table <span class="ot">&lt;-</span>results_table <span class="sc">%&gt;%</span>  <span class="fu">bind_rows</span>(results_curr)</span>
<span id="cb20-288"><a href="#cb20-288" aria-hidden="true" tabindex="-1"></a>results_table</span>
<span id="cb20-289"><a href="#cb20-289" aria-hidden="true" tabindex="-1"></a>reg_emp_stat_fit <span class="ot">&lt;-</span> reg_spec <span class="sc">%&gt;%</span> </span>
<span id="cb20-290"><a href="#cb20-290" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(Salary <span class="sc">~</span> .<span class="sc">-</span>age_log<span class="sc">-</span>PerformanceScore<span class="sc">-</span>DaysLateLast30<span class="sc">-</span>ManagerName<span class="sc">-</span>Married<span class="sc">-</span>Age<span class="sc">-</span>GenderCode<span class="sc">-</span>Gender<span class="sc">-</span>EmploymentStatus, </span>
<span id="cb20-291"><a href="#cb20-291" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> df_original)</span>
<span id="cb20-292"><a href="#cb20-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-293"><a href="#cb20-293" aria-hidden="true" tabindex="-1"></a>mae <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">mean</span>(<span class="fu">abs</span>(reg_emp_stat_fit<span class="sc">$</span>fit<span class="sc">$</span>residual)))</span>
<span id="cb20-294"><a href="#cb20-294" aria-hidden="true" tabindex="-1"></a>glance_status <span class="ot">&lt;-</span> <span class="fu">glance</span>(<span class="fu">summary</span>(reg_emp_stat_fit<span class="sc">$</span>fit)) </span>
<span id="cb20-295"><a href="#cb20-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-296"><a href="#cb20-296" aria-hidden="true" tabindex="-1"></a>results_curr <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">Model =</span> <span class="st">'- EmpStatus'</span>,</span>
<span id="cb20-297"><a href="#cb20-297" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Pruned_Variables =</span> <span class="st">"Above + EmpStatus"</span>,</span>
<span id="cb20-298"><a href="#cb20-298" aria-hidden="true" tabindex="-1"></a>                              <span class="at">R_Square =</span> glance_status<span class="sc">$</span>r.squared,</span>
<span id="cb20-299"><a href="#cb20-299" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Adj_R_Square =</span> glance_status<span class="sc">$</span>adj.r.squared,</span>
<span id="cb20-300"><a href="#cb20-300" aria-hidden="true" tabindex="-1"></a>                              <span class="at">MAE =</span> mae)</span>
<span id="cb20-301"><a href="#cb20-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-302"><a href="#cb20-302" aria-hidden="true" tabindex="-1"></a>results_table <span class="ot">&lt;-</span>results_table <span class="sc">%&gt;%</span>  <span class="fu">bind_rows</span>(results_curr)</span>
<span id="cb20-303"><a href="#cb20-303" aria-hidden="true" tabindex="-1"></a>results_table</span>
<span id="cb20-304"><a href="#cb20-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-305"><a href="#cb20-305" aria-hidden="true" tabindex="-1"></a>reg_eng_sur_fit <span class="ot">&lt;-</span> reg_spec <span class="sc">%&gt;%</span> </span>
<span id="cb20-306"><a href="#cb20-306" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(Salary <span class="sc">~</span> .<span class="sc">-</span>age_log<span class="sc">-</span>PerformanceScore<span class="sc">-</span>DaysLateLast30<span class="sc">-</span>ManagerName<span class="sc">-</span>Married<span class="sc">-</span>Age<span class="sc">-</span>GenderCode<span class="sc">-</span>Gender<span class="sc">-</span>EmploymentStatus<span class="sc">-</span>EngagementSurvey, </span>
<span id="cb20-307"><a href="#cb20-307" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> df_original)</span>
<span id="cb20-308"><a href="#cb20-308" aria-hidden="true" tabindex="-1"></a>mae <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">mean</span>(<span class="fu">abs</span>(reg_eng_sur_fit<span class="sc">$</span>fit<span class="sc">$</span>residual)))</span>
<span id="cb20-309"><a href="#cb20-309" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-310"><a href="#cb20-310" aria-hidden="true" tabindex="-1"></a>glance_survey<span class="ot">&lt;-</span> <span class="fu">glance</span>(<span class="fu">summary</span>(reg_eng_sur_fit<span class="sc">$</span>fit)) </span>
<span id="cb20-311"><a href="#cb20-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-312"><a href="#cb20-312" aria-hidden="true" tabindex="-1"></a>results_curr <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">Model =</span> <span class="st">'- Survey'</span>,</span>
<span id="cb20-313"><a href="#cb20-313" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Pruned_Variables =</span> <span class="st">"Above + Survey"</span>,</span>
<span id="cb20-314"><a href="#cb20-314" aria-hidden="true" tabindex="-1"></a>                              <span class="at">R_Square =</span> glance_survey<span class="sc">$</span>r.squared,</span>
<span id="cb20-315"><a href="#cb20-315" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Adj_R_Square =</span> glance_survey<span class="sc">$</span>adj.r.squared,</span>
<span id="cb20-316"><a href="#cb20-316" aria-hidden="true" tabindex="-1"></a>                              <span class="at">MAE =</span> mae)</span>
<span id="cb20-317"><a href="#cb20-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-318"><a href="#cb20-318" aria-hidden="true" tabindex="-1"></a>results_table <span class="ot">&lt;-</span>results_table <span class="sc">%&gt;%</span>  <span class="fu">bind_rows</span>(results_curr)</span>
<span id="cb20-319"><a href="#cb20-319" aria-hidden="true" tabindex="-1"></a>results_table</span>
<span id="cb20-320"><a href="#cb20-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-321"><a href="#cb20-321" aria-hidden="true" tabindex="-1"></a>reg_abs_fit <span class="ot">&lt;-</span> reg_spec <span class="sc">%&gt;%</span> </span>
<span id="cb20-322"><a href="#cb20-322" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(Salary <span class="sc">~</span> .<span class="sc">-</span>age_log<span class="sc">-</span>PerformanceScore<span class="sc">-</span>DaysLateLast30<span class="sc">-</span>ManagerName<span class="sc">-</span>Married<span class="sc">-</span>Age<span class="sc">-</span>GenderCode<span class="sc">-</span>Gender<span class="sc">-</span>EmploymentStatus<span class="sc">-</span>EngagementSurvey<span class="sc">-</span>Absences, </span>
<span id="cb20-323"><a href="#cb20-323" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> df_original)</span>
<span id="cb20-324"><a href="#cb20-324" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-325"><a href="#cb20-325" aria-hidden="true" tabindex="-1"></a>mae <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">mean</span>(<span class="fu">abs</span>(reg_abs_fit<span class="sc">$</span>fit<span class="sc">$</span>residual)))</span>
<span id="cb20-326"><a href="#cb20-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-327"><a href="#cb20-327" aria-hidden="true" tabindex="-1"></a>glance_absence<span class="ot">&lt;-</span> <span class="fu">glance</span>(<span class="fu">summary</span>(reg_abs_fit<span class="sc">$</span>fit)) </span>
<span id="cb20-328"><a href="#cb20-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-329"><a href="#cb20-329" aria-hidden="true" tabindex="-1"></a>results_curr <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">Model =</span> <span class="st">'- Absence'</span>,</span>
<span id="cb20-330"><a href="#cb20-330" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Pruned_Variables =</span> <span class="st">"Above + Absence"</span>,</span>
<span id="cb20-331"><a href="#cb20-331" aria-hidden="true" tabindex="-1"></a>                              <span class="at">R_Square =</span> glance_absence<span class="sc">$</span>r.squared,</span>
<span id="cb20-332"><a href="#cb20-332" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Adj_R_Square =</span> glance_absence<span class="sc">$</span>adj.r.squared,</span>
<span id="cb20-333"><a href="#cb20-333" aria-hidden="true" tabindex="-1"></a>                              <span class="at">MAE =</span> mae)</span>
<span id="cb20-334"><a href="#cb20-334" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-335"><a href="#cb20-335" aria-hidden="true" tabindex="-1"></a>results_table <span class="ot">&lt;-</span>results_table <span class="sc">%&gt;%</span>  <span class="fu">bind_rows</span>(results_curr)</span>
<span id="cb20-336"><a href="#cb20-336" aria-hidden="true" tabindex="-1"></a>results_table</span>
<span id="cb20-337"><a href="#cb20-337" aria-hidden="true" tabindex="-1"></a>reg_emp_satis <span class="ot">&lt;-</span> reg_spec <span class="sc">%&gt;%</span> </span>
<span id="cb20-338"><a href="#cb20-338" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(Salary <span class="sc">~</span> .<span class="sc">-</span>age_log<span class="sc">-</span>PerformanceScore<span class="sc">-</span>DaysLateLast30<span class="sc">-</span>ManagerName<span class="sc">-</span>Married<span class="sc">-</span>Age<span class="sc">-</span>GenderCode<span class="sc">-</span>Gender<span class="sc">-</span>EmploymentStatus<span class="sc">-</span>EngagementSurvey<span class="sc">-</span>Absences<span class="sc">-</span>EmpSatisfaction, </span>
<span id="cb20-339"><a href="#cb20-339" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> df_original)</span>
<span id="cb20-340"><a href="#cb20-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-341"><a href="#cb20-341" aria-hidden="true" tabindex="-1"></a>mae <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">mean</span>(<span class="fu">abs</span>(reg_emp_satis<span class="sc">$</span>fit<span class="sc">$</span>residual)))</span>
<span id="cb20-342"><a href="#cb20-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-343"><a href="#cb20-343" aria-hidden="true" tabindex="-1"></a>glance_satisfaction<span class="ot">&lt;-</span> <span class="fu">glance</span>(<span class="fu">summary</span>(reg_emp_satis<span class="sc">$</span>fit))</span>
<span id="cb20-344"><a href="#cb20-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-345"><a href="#cb20-345" aria-hidden="true" tabindex="-1"></a>results_curr <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">Model =</span> <span class="st">'- Satisfaction'</span>,</span>
<span id="cb20-346"><a href="#cb20-346" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Pruned_Variables =</span> <span class="st">"Above + Satisfaction"</span>,</span>
<span id="cb20-347"><a href="#cb20-347" aria-hidden="true" tabindex="-1"></a>                              <span class="at">R_Square =</span> glance_satisfaction<span class="sc">$</span>r.squared,</span>
<span id="cb20-348"><a href="#cb20-348" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Adj_R_Square =</span> glance_satisfaction<span class="sc">$</span>adj.r.squared,</span>
<span id="cb20-349"><a href="#cb20-349" aria-hidden="true" tabindex="-1"></a>                              <span class="at">MAE =</span> mae)</span>
<span id="cb20-350"><a href="#cb20-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-351"><a href="#cb20-351" aria-hidden="true" tabindex="-1"></a>results_table <span class="ot">&lt;-</span>results_table <span class="sc">%&gt;%</span>  <span class="fu">bind_rows</span>(results_curr)</span>
<span id="cb20-352"><a href="#cb20-352" aria-hidden="true" tabindex="-1"></a>results_table</span>
<span id="cb20-353"><a href="#cb20-353" aria-hidden="true" tabindex="-1"></a>reg_job_fair <span class="ot">&lt;-</span> reg_spec <span class="sc">%&gt;%</span> </span>
<span id="cb20-354"><a href="#cb20-354" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(Salary <span class="sc">~</span> .<span class="sc">-</span>age_log<span class="sc">-</span>PerformanceScore<span class="sc">-</span>DaysLateLast30<span class="sc">-</span>ManagerName<span class="sc">-</span>Married<span class="sc">-</span>Age<span class="sc">-</span>GenderCode<span class="sc">-</span>Gender<span class="sc">-</span>EmploymentStatus<span class="sc">-</span>EngagementSurvey<span class="sc">-</span>Absences<span class="sc">-</span>EmpSatisfaction<span class="sc">-</span>FromDiversityJobFair, </span>
<span id="cb20-355"><a href="#cb20-355" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> df_original)</span>
<span id="cb20-356"><a href="#cb20-356" aria-hidden="true" tabindex="-1"></a>mae <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">mean</span>(<span class="fu">abs</span>(reg_job_fair<span class="sc">$</span>fit<span class="sc">$</span>residual)))</span>
<span id="cb20-357"><a href="#cb20-357" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-358"><a href="#cb20-358" aria-hidden="true" tabindex="-1"></a>glance_job_fair<span class="ot">&lt;-</span> <span class="fu">glance</span>(<span class="fu">summary</span>(reg_job_fair<span class="sc">$</span>fit)) </span>
<span id="cb20-359"><a href="#cb20-359" aria-hidden="true" tabindex="-1"></a>results_curr <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">Model =</span> <span class="st">'- JobFair'</span>,</span>
<span id="cb20-360"><a href="#cb20-360" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Pruned_Variables =</span> <span class="st">"Above + Job Fair"</span>,</span>
<span id="cb20-361"><a href="#cb20-361" aria-hidden="true" tabindex="-1"></a>                              <span class="at">R_Square =</span> glance_job_fair<span class="sc">$</span>r.squared,</span>
<span id="cb20-362"><a href="#cb20-362" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Adj_R_Square =</span> glance_job_fair<span class="sc">$</span>adj.r.squared,</span>
<span id="cb20-363"><a href="#cb20-363" aria-hidden="true" tabindex="-1"></a>                              <span class="at">MAE =</span> mae)</span>
<span id="cb20-364"><a href="#cb20-364" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-365"><a href="#cb20-365" aria-hidden="true" tabindex="-1"></a>results_table <span class="ot">&lt;-</span>results_table <span class="sc">%&gt;%</span>  <span class="fu">bind_rows</span>(results_curr)</span>
<span id="cb20-366"><a href="#cb20-366" aria-hidden="true" tabindex="-1"></a>results_table</span>
<span id="cb20-367"><a href="#cb20-367" aria-hidden="true" tabindex="-1"></a>final_model <span class="ot">&lt;-</span> reg_emp_satis</span>
<span id="cb20-368"><a href="#cb20-368" aria-hidden="true" tabindex="-1"></a>pred_final_model <span class="ot">&lt;-</span> final_model<span class="sc">$</span>fit <span class="sc">%&gt;%</span></span>
<span id="cb20-369"><a href="#cb20-369" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(df_original) </span>
<span id="cb20-370"><a href="#cb20-370" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-371"><a href="#cb20-371" aria-hidden="true" tabindex="-1"></a>pred_final_model <span class="sc">%&gt;%</span></span>
<span id="cb20-372"><a href="#cb20-372" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> .fitted, <span class="at">x =</span> Salary)) <span class="sc">+</span> </span>
<span id="cb20-373"><a href="#cb20-373" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">col =</span> <span class="st">"#6e0000"</span>) <span class="sc">+</span></span>
<span id="cb20-374"><a href="#cb20-374" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">col =</span> <span class="st">"gold"</span>) <span class="sc">+</span> </span>
<span id="cb20-375"><a href="#cb20-375" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Predicted vs Actual Salary for Final Model"</span>,</span>
<span id="cb20-376"><a href="#cb20-376" aria-hidden="true" tabindex="-1"></a>          <span class="at">subtitle=</span><span class="fu">paste</span>(<span class="st">"Adj R-Squared:"</span>,</span>
<span id="cb20-377"><a href="#cb20-377" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">round</span>(<span class="fu">glance</span>(final_model)<span class="sc">$</span>adj.r.squared,<span class="dv">4</span>),</span>
<span id="cb20-378"><a href="#cb20-378" aria-hidden="true" tabindex="-1"></a>                         <span class="st">"  Mean Abs Residuals:"</span>,</span>
<span id="cb20-379"><a href="#cb20-379" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">round</span>(<span class="fu">mean</span>(<span class="fu">abs</span>(pred_final_model<span class="sc">$</span>.resid)),<span class="dv">4</span>)))</span>
<span id="cb20-380"><a href="#cb20-380" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-381"><a href="#cb20-381" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-382"><a href="#cb20-382" aria-hidden="true" tabindex="-1"></a>results_table</span>
<span id="cb20-383"><a href="#cb20-383" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(final_model<span class="sc">$</span>fit)</span>
<span id="cb20-384"><a href="#cb20-384" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-385"><a href="#cb20-385" aria-hidden="true" tabindex="-1"></a>lm_inter <span class="ot">&lt;-</span> reg_spec <span class="sc">%&gt;%</span> </span>
<span id="cb20-386"><a href="#cb20-386" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(Salary <span class="sc">~</span> SpecialProjectsCount <span class="sc">+</span> TimeEmployed <span class="sc">+</span> Department <span class="sc">+</span> mgr_comb, <span class="at">data =</span> df_original)</span>
<span id="cb20-387"><a href="#cb20-387" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-388"><a href="#cb20-388" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(lm_inter<span class="sc">$</span>fit) <span class="sc">%&gt;%</span> </span>
<span id="cb20-389"><a href="#cb20-389" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span> (<span class="at">digits=</span><span class="dv">4</span>)</span>
<span id="cb20-390"><a href="#cb20-390" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-391"><a href="#cb20-391" aria-hidden="true" tabindex="-1"></a>glance_inter <span class="ot">&lt;-</span> <span class="fu">glance</span>(<span class="fu">summary</span>(lm_inter<span class="sc">$</span>fit))</span>
<span id="cb20-392"><a href="#cb20-392" aria-hidden="true" tabindex="-1"></a>glance_inter <span class="sc">%&gt;%</span> <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">4</span>)</span>
<span id="cb20-393"><a href="#cb20-393" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-394"><a href="#cb20-394" aria-hidden="true" tabindex="-1"></a>results_curr <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">Model =</span> <span class="st">'lm + interactions'</span>,</span>
<span id="cb20-395"><a href="#cb20-395" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Pruned_Variables =</span> <span class="st">"Interactions"</span>,</span>
<span id="cb20-396"><a href="#cb20-396" aria-hidden="true" tabindex="-1"></a>                              <span class="at">R_Square =</span> glance_inter<span class="sc">$</span>r.squared,</span>
<span id="cb20-397"><a href="#cb20-397" aria-hidden="true" tabindex="-1"></a>                              <span class="at">Adj_R_Square =</span> glance_inter<span class="sc">$</span>adj.r.squared,</span>
<span id="cb20-398"><a href="#cb20-398" aria-hidden="true" tabindex="-1"></a>                              <span class="at">MAE =</span> mae)</span>
<span id="cb20-399"><a href="#cb20-399" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-400"><a href="#cb20-400" aria-hidden="true" tabindex="-1"></a>results_table <span class="ot">&lt;-</span>results_table <span class="sc">%&gt;%</span>  <span class="fu">bind_rows</span>(results_curr)</span>
<span id="cb20-401"><a href="#cb20-401" aria-hidden="true" tabindex="-1"></a>results_table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>